### ISSUE TITLE
Misspelling of "intended" in readme

### ISSUE THREAD

**Issue by danielj-n** [ZakSN/rtx#1]
"Linewraps at 80 as god inteneded"

I am in disbelief such a spelling error made it through to the rtx main branch. It's as if this is an Amateur project of some kind.

**Comment by ZakSN** [comment]
if you'd read the history you see that the README is a work in progress. from 0b91e126cf61da2e80f75c24942fca08c69eea4c:

add README, not nearly done

as such readme should not be considered stable.
