### ISSUE TITLE
Cannot backspace in rtx

### ISSUE THREAD

**Issue by danielj-n** [ZakSN/rtx#2]
Is this a bug or a feature? Is this planned to be added in future updates or should it already be there?

**Comment by ZakSN** [comment]
Read over the input handling logic in rtx mode. Input is on a per key basis, and so backspace is not supported yet. backspace should work as expected in tx mode.

**Comment by danielj-n** [comment]
ah I see, all good

**Comment by ZakSN** [comment]
check out the 'better_input' branch. It is still quite buggy, but it has basic support for input buffer editing, backspace, left and right arrows and delete

**Comment by ZakSN** [comment]
Feature is now in master. Issue closed.

Note that this removes the ability to 'draw' since `rtx` now captures arrow keys. I believe this is a better way of handling input, but I may decide to add a switch to allow the old system of transmitting arrow keys...
